# coding: utf-8

xss_test_data = [
    # r"ABCD",
    # r"<>?:\"{}|_+",
    # r"\u0001\u0002\u0003\u0004\u0005\u0006\u0007\b\u000e\u000f\u0010\u0011\u0012\u0013\u0014\u0015\u0016\u0017\u0018\u0019\u001a\u001b\u001c\u001d\u001e\u001f",
    # r"<script>alert(123)</script>",
    # r"&lt;script&gt;alert(&#39;123&#39;);&lt;/script&gt;",
    # r"<img src=x onerror=alert(123) />",
    # r"<svg><script>123<1>alert(123)</script>",
    # r"\"><script>alert(123)</script>",
    # r"'><script>alert(123)</script>",
    # r"><script>alert(123)</script>",
    # r"</script><script>alert(123)</script>",
    # r"< / script >< script >alert(123)< / script >",
    # r" onfocus=JaVaSCript:alert(123) autofocus",
    # r"\" onfocus=JaVaSCript:alert(123) autofocus",
    # r"' onfocus=JaVaSCript:alert(123) autofocus",
    # r"<sc<script>ript>alert(123)</sc</script>ript>",
    # r"--><script>alert(123)</script>",
    # r"\";alert(123);t=\"",
    # r"';alert(123);t='",
    # r"JavaSCript:alert(123)",
    # r";alert(123);",
    # r"src=JaVaSCript:prompt(132)",
    # r"\"><script>alert(123);</script x=\"",
    # r"'><script>alert(123);</script x='",
    # r"><script>alert(123);</script x=",
    # r"\" autofocus onkeyup=\"javascript:alert(123)",
    # r"' autofocus onkeyup='javascript:alert(123)",
    # r"<script\\x20type=\"text/javascript\">javascript:alert(1);</script>",
    # r"<script\\x3Etype=\"text/javascript\">javascript:alert(1);</script>",
    # r"<script\\x0Dtype=\"text/javascript\">javascript:alert(1);</script>",
    # r"<script\\x09type=\"text/javascript\">javascript:alert(1);</script>",
    # r"<script\\x0Ctype=\"text/javascript\">javascript:alert(1);</script>",
    # r"<script\\x2Ftype=\"text/javascript\">javascript:alert(1);</script>",
    # r"<script\\x0Atype=\"text/javascript\">javascript:alert(1);</script>",
    # r"'`\"><\\x3Cscript>javascript:alert(1)</script>",
    # r"'`\"><\\x00script>javascript:alert(1)</script>",
    # r"ABC<div style=\"x\\x3Aexpression(javascript:alert(1)\">DEF",
    # r"ABC<div style=\"x:expression\\x5C(javascript:alert(1)\">DEF",
    # r"ABC<div style=\"x:expression\\x00(javascript:alert(1)\">DEF",
    # r"ABC<div style=\"x:exp\\x00ression(javascript:alert(1)\">DEF",
    # r"ABC<div style=\"x:exp\\x5Cression(javascript:alert(1)\">DEF",
    # r"ABC<div style=\"x:\\x0Aexpression(javascript:alert(1)\">DEF",
    # r"ABC<div style=\"x:\\x09expression(javascript:alert(1)\">DEF",
    # r"ABC<div style=\"x:\\xE3\\x80\\x80expression(javascript:alert(1)\">DEF",
    # r"ABC<div style=\"x:\\xE2\\x80\\x84expression(javascript:alert(1)\">DEF",
    # r"ABC<div style=\"x:\\xC2\\xA0expression(javascript:alert(1)\">DEF",
    # r"ABC<div style=\"x:\\xE2\\x80\\x80expression(javascript:alert(1)\">DEF",
    # r"ABC<div style=\"x:\\xE2\\x80\\x8Aexpression(javascript:alert(1)\">DEF",
    # r"ABC<div style=\"x:\\x0Dexpression(javascript:alert(1)\">DEF",
    # r"ABC<div style=\"x:\\x0Cexpression(javascript:alert(1)\">DEF",
    # r"ABC<div style=\"x:\\xE2\\x80\\x87expression(javascript:alert(1)\">DEF",
    # r"ABC<div style=\"x:\\xEF\\xBB\\xBFexpression(javascript:alert(1)\">DEF",
    # r"ABC<div style=\"x:\\x20expression(javascript:alert(1)\">DEF",
    # r"ABC<div style=\"x:\\xE2\\x80\\x88expression(javascript:alert(1)\">DEF",
    # r"ABC<div style=\"x:\\x00expression(javascript:alert(1)\">DEF",
    # r"ABC<div style=\"x:\\xE2\\x80\\x8Bexpression(javascript:alert(1)\">DEF",
    # r"ABC<div style=\"x:\\xE2\\x80\\x86expression(javascript:alert(1)\">DEF",
    # r"ABC<div style=\"x:\\xE2\\x80\\x85expression(javascript:alert(1)\">DEF",
    # r"ABC<div style=\"x:\\xE2\\x80\\x82expression(javascript:alert(1)\">DEF",
    # r"ABC<div style=\"x:\\x0Bexpression(javascript:alert(1)\">DEF",
    # r"ABC<div style=\"x:\\xE2\\x80\\x81expression(javascript:alert(1)\">DEF",
    # r"ABC<div style=\"x:\\xE2\\x80\\x83expression(javascript:alert(1)\">DEF",
    # r"ABC<div style=\"x:\\xE2\\x80\\x89expression(javascript:alert(1)\">DEF",
    # r"<a href=\"\\x0Bjavascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>",
    # r"<a href=\"\\x0Fjavascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>",
    # r"<a href=\"\\xC2\\xA0javascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>",
    # r"<a href=\"\\x05javascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>",
    # r"<a href=\"\\xE1\\xA0\\x8Ejavascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>",
    # r"<a href=\"\\x18javascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>",
    # r"<a href=\"\\x11javascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>",
    # r"<a href=\"\\xE2\\x80\\x88javascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>",
    # r"<a href=\"\\xE2\\x80\\x89javascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>",
    # r"<a href=\"\\xE2\\x80\\x80javascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>",
    # r"<a href=\"\\x17javascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>",
    # r"<a href=\"\\x03javascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>",
    # r"<a href=\"\\x0Ejavascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>",
    # r"<a href=\"\\x1Ajavascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>",
    # r"<a href=\"\\x00javascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>",
    # r"<a href=\"\\x10javascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>",
    # r"<a href=\"\\xE2\\x80\\x82javascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>",
    # r"<a href=\"\\x20javascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>",
    # r"<a href=\"\\x13javascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>",
    # r"<a href=\"\\x09javascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>",
    # r"<a href=\"\\xE2\\x80\\x8Ajavascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>",
    # r"<a href=\"\\x14javascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>",
    # r"<a href=\"\\x19javascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>",
    # r"<a href=\"\\xE2\\x80\\xAFjavascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>",
    # r"<a href=\"\\x1Fjavascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>",
    # r"<a href=\"\\xE2\\x80\\x81javascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>",
    # r"<a href=\"\\x1Djavascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>",
    # r"<a href=\"\\xE2\\x80\\x87javascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>",
    # r"<a href=\"\\x07javascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>",
    # r"<a href=\"\\xE1\\x9A\\x80javascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>",
    # r"<a href=\"\\xE2\\x80\\x83javascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>",
    # r"<a href=\"\\x04javascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>",
    # r"<a href=\"\\x01javascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>",
    # r"<a href=\"\\x08javascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>",
    # r"<a href=\"\\xE2\\x80\\x84javascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>",
    # r"<a href=\"\\xE2\\x80\\x86javascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>",
    # r"<a href=\"\\xE3\\x80\\x80javascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>",
    # r"<a href=\"\\x12javascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>",
    # r"<a href=\"\\x0Djavascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>",
    # r"<a href=\"\\x0Ajavascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>",
    # r"<a href=\"\\x0Cjavascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>",
    # r"<a href=\"\\x15javascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>",
    # r"<a href=\"\\xE2\\x80\\xA8javascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>",
    # r"<a href=\"\\x16javascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>",
    # r"<a href=\"\\x02javascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>",
    # r"<a href=\"\\x1Bjavascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>",
    # r"<a href=\"\\x06javascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>",
    # r"<a href=\"\\xE2\\x80\\xA9javascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>",
    # r"<a href=\"\\xE2\\x80\\x85javascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>",
    # r"<a href=\"\\x1Ejavascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>",
    # r"<a href=\"\\xE2\\x81\\x9Fjavascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>",
    # r"<a href=\"\\x1Cjavascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>",
    # r"<a href=\"javascript\\x00:javascript:alert(1)\" id=\"fuzzelement1\">test</a>",
    # r"<a href=\"javascript\\x3A:javascript:alert(1)\" id=\"fuzzelement1\">test</a>",
    # r"<a href=\"javascript\\x09:javascript:alert(1)\" id=\"fuzzelement1\">test</a>",
    # r"<a href=\"javascript\\x0D:javascript:alert(1)\" id=\"fuzzelement1\">test</a>",
    # r"<a href=\"javascript\\x0A:javascript:alert(1)\" id=\"fuzzelement1\">test</a>",
    # r"`\"'><img src=xxx:x \\x0Aonerror=javascript:alert(1)>",
    # r"`\"'><img src=xxx:x \\x22onerror=javascript:alert(1)>",
    # r"`\"'><img src=xxx:x \\x0Bonerror=javascript:alert(1)>",
    # r"`\"'><img src=xxx:x \\x0Donerror=javascript:alert(1)>",
    # r"`\"'><img src=xxx:x \\x2Fonerror=javascript:alert(1)>",
    # r"`\"'><img src=xxx:x \\x09onerror=javascript:alert(1)>",
    # r"`\"'><img src=xxx:x \\x0Conerror=javascript:alert(1)>",
    # r"`\"'><img src=xxx:x \\x00onerror=javascript:alert(1)>",
    # r"`\"'><img src=xxx:x \\x27onerror=javascript:alert(1)>",
    # r"`\"'><img src=xxx:x \\x20onerror=javascript:alert(1)>",
    # r"\"`'><script>\\x3Bjavascript:alert(1)</script>",
    # r"\"`'><script>\\x0Djavascript:alert(1)</script>",
    # r"\"`'><script>\\xEF\\xBB\\xBFjavascript:alert(1)</script>",
    # r"\"`'><script>\\xE2\\x80\\x81javascript:alert(1)</script>",
    # r"\"`'><script>\\xE2\\x80\\x84javascript:alert(1)</script>",
    # r"\"`'><script>\\xE3\\x80\\x80javascript:alert(1)</script>",
    # r"\"`'><script>\\x09javascript:alert(1)</script>",
    # r"\"`'><script>\\xE2\\x80\\x89javascript:alert(1)</script>",
    # r"\"`'><script>\\xE2\\x80\\x85javascript:alert(1)</script>",
    # r"\"`'><script>\\xE2\\x80\\x88javascript:alert(1)</script>",
    # r"\"`'><script>\\x00javascript:alert(1)</script>",
    # r"\"`'><script>\\xE2\\x80\\xA8javascript:alert(1)</script>",
    # r"\"`'><script>\\xE2\\x80\\x8Ajavascript:alert(1)</script>",
    # r"\"`'><script>\\xE1\\x9A\\x80javascript:alert(1)</script>",
    # r"\"`'><script>\\x0Cjavascript:alert(1)</script>",
    # r"\"`'><script>\\x2Bjavascript:alert(1)</script>",
    # r"\"`'><script>\\xF0\\x90\\x96\\x9Ajavascript:alert(1)</script>",
    # r"\"`'><script>-javascript:alert(1)</script>",
    # r"\"`'><script>\\x0Ajavascript:alert(1)</script>",
    # r"\"`'><script>\\xE2\\x80\\xAFjavascript:alert(1)</script>",
    # r"\"`'><script>\\x7Ejavascript:alert(1)</script>",
    # r"\"`'><script>\\xE2\\x80\\x87javascript:alert(1)</script>",
    # r"\"`'><script>\\xE2\\x81\\x9Fjavascript:alert(1)</script>",
    # r"\"`'><script>\\xE2\\x80\\xA9javascript:alert(1)</script>",
    # r"\"`'><script>\\xC2\\x85javascript:alert(1)</script>",
    # r"\"`'><script>\\xEF\\xBF\\xAEjavascript:alert(1)</script>",
    # r"\"`'><script>\\xE2\\x80\\x83javascript:alert(1)</script>",
    # r"\"`'><script>\\xE2\\x80\\x8Bjavascript:alert(1)</script>",
    # r"\"`'><script>\\xEF\\xBF\\xBEjavascript:alert(1)</script>",
    # r"\"`'><script>\\xE2\\x80\\x80javascript:alert(1)</script>",
    # r"\"`'><script>\\x21javascript:alert(1)</script>",
    # r"\"`'><script>\\xE2\\x80\\x82javascript:alert(1)</script>",
    # r"\"`'><script>\\xE2\\x80\\x86javascript:alert(1)</script>",
    # r"\"`'><script>\\xE1\\xA0\\x8Ejavascript:alert(1)</script>",
    # r"\"`'><script>\\x0Bjavascript:alert(1)</script>",
    # r"\"`'><script>\\x20javascript:alert(1)</script>",
    # r"\"`'><script>\\xC2\\xA0javascript:alert(1)</script>",
    # r"<img \\x00src=x onerror=\"alert(1)\">",
    # r"<img \\x47src=x onerror=\"javascript:alert(1)\">",
    # r"<img \\x11src=x onerror=\"javascript:alert(1)\">",
    # r"<img \\x12src=x onerror=\"javascript:alert(1)\">",
    # r"<img\\x47src=x onerror=\"javascript:alert(1)\">",
    # r"<img\\x10src=x onerror=\"javascript:alert(1)\">",
    # r"<img\\x13src=x onerror=\"javascript:alert(1)\">",
    # r"<img\\x32src=x onerror=\"javascript:alert(1)\">",
    # r"<img\\x47src=x onerror=\"javascript:alert(1)\">",
    # r"<img\\x11src=x onerror=\"javascript:alert(1)\">",
    # r"<img \\x47src=x onerror=\"javascript:alert(1)\">",
    # r"<img \\x34src=x onerror=\"javascript:alert(1)\">",
    # r"<img \\x39src=x onerror=\"javascript:alert(1)\">",
    # r"<img \\x00src=x onerror=\"javascript:alert(1)\">",
    # r"<img src\\x09=x onerror=\"javascript:alert(1)\">",
    # r"<img src\\x10=x onerror=\"javascript:alert(1)\">",
    # r"<img src\\x13=x onerror=\"javascript:alert(1)\">",
    # r"<img src\\x32=x onerror=\"javascript:alert(1)\">",
    # r"<img src\\x12=x onerror=\"javascript:alert(1)\">",
    # r"<img src\\x11=x onerror=\"javascript:alert(1)\">",
    # r"<img src\\x00=x onerror=\"javascript:alert(1)\">",
    # r"<img src\\x47=x onerror=\"javascript:alert(1)\">",
    # r"<img src=x\\x09onerror=\"javascript:alert(1)\">",
    # r"<img src=x\\x10onerror=\"javascript:alert(1)\">",
    # r"<img src=x\\x11onerror=\"javascript:alert(1)\">",
    # r"<img src=x\\x12onerror=\"javascript:alert(1)\">",
    # r"<img src=x\\x13onerror=\"javascript:alert(1)\">",
    # r"<img[a][b][c]src[d]=x[e]onerror=[f]\"alert(1)\">",
    # r"<img src=x onerror=\\x09\"javascript:alert(1)\">",
    # r"<img src=x onerror=\\x10\"javascript:alert(1)\">",
    # r"<img src=x onerror=\\x11\"javascript:alert(1)\">",
    # r"<img src=x onerror=\\x12\"javascript:alert(1)\">",
    # r"<img src=x onerror=\\x32\"javascript:alert(1)\">",
    # r"<img src=x onerror=\\x00\"javascript:alert(1)\">",
    # r"<a href=java&#1&#2&#3&#4&#5&#6&#7&#8&#11&#12script:javascript:alert(1)>XXX</a>",
    # r"<img src=\"x` `<script>javascript:alert(1)</script>\"` `>",
    # r"<img src onerror /\" '\"= alt=javascript:alert(1)//\">",
    # r"<title onpropertychange=javascript:alert(1)></title><title title=>",
    # r"<a href=http://foo.bar/#x=`y></a><img alt=\"`><img src=x:x onerror=javascript:alert(1)></a>\">",
    # r"<!--[if]><script>javascript:alert(1)</script -->",
    # r"<!--[if<img src=x onerror=javascript:alert(1)//]> -->",
    # r"<script src=\"/\\%(jscript)s\"></script>",
    # r"<script src=\"\\\\%(jscript)s\"></script>",
    # r"<IMG \"\"\"><SCRIPT>alert(\"XSS\")</SCRIPT>\">",
    # r"<IMG SRC=javascript:alert(String.fromCharCode(88,83,83))>",
    # r"<IMG SRC=# onmouseover=\"alert('xxs')\">",
    # r"<IMG SRC= onmouseover=\"alert('xxs')\">",
    # r"<IMG onmouseover=\"alert('xxs')\">",
    # r"<IMG SRC=&#106;&#97;&#118;&#97;&#115;&#99;&#114;&#105;&#112;&#116;&#58;&#97;&#108;&#101;&#114;&#116;&#40;&#39;&#88;&#83;&#83;&#39;&#41;>",
    # r"<IMG SRC=&#0000106&#0000097&#0000118&#0000097&#0000115&#0000099&#0000114&#0000105&#0000112&#0000116&#0000058&#0000097&#0000108&#0000101&#0000114&#0000116&#0000040&#0000039&#0000088&#0000083&#0000083&#0000039&#0000041>",
    # r"<IMG SRC=&#x6A&#x61&#x76&#x61&#x73&#x63&#x72&#x69&#x70&#x74&#x3A&#x61&#x6C&#x65&#x72&#x74&#x28&#x27&#x58&#x53&#x53&#x27&#x29>",
    # r"<IMG SRC=\"jav   ascript:alert('XSS');\">",
    # r"<IMG SRC=\"jav&#x09;ascript:alert('XSS');\">",
    # r"<IMG SRC=\"jav&#x0A;ascript:alert('XSS');\">",
    # r"<IMG SRC=\"jav&#x0D;ascript:alert('XSS');\">",
    # r"perl -e 'print \"<IMG SRC=java\\0script:alert(\\\"XSS\\\")>\";' > out",
    # r"<IMG SRC=\" &#14;  javascript:alert('XSS');\">",
    # r"<SCRIPT/XSS SRC=\"http://ha.ckers.org/xss.js\"></SCRIPT>",
    # r"<BODY onload!#$%&()*~+-_.,:;?@[/|\\]^`=alert(\"XSS\")>",
    # r"<SCRIPT/SRC=\"http://ha.ckers.org/xss.js\"></SCRIPT>",
    # r"<<SCRIPT>alert(\"XSS\");//<</SCRIPT>",
    # r"<SCRIPT SRC=http://ha.ckers.org/xss.js?< B >",
    # r"<SCRIPT SRC=//ha.ckers.org/.j>",
    # r"<IMG SRC=\"javascript:alert('XSS')\"",
    # r"<iframe src=http://ha.ckers.org/scriptlet.html <",
    # r"\\\";alert('XSS');//",
    # r"<u oncopy=alert()> Copy me</u>",
    # r"<i onwheel=alert(1)> Scroll over me </i>",
    # r"http://a/%%30%30",
    # r"</textarea><script>alert(123)</script>",
    # r"@{[system \"touch /tmp/blns.fail\"]}",
    # r"eval(\"puts 'hello world'\")",
    # r"System(\"ls -al /\")",
    # r"Kernel.exec(\"ls -al /\")",
    # r"<?xml version=\"1.0\" encoding=\"ISO-8859-1\"?><!DOCTYPE foo [ <!ELEMENT foo ANY ><!ENTITY xxe SYSTEM \"file:///etc/passwd\" >]><foo>&xxe;</foo>",
    # r"%d",
    # r"../../../../../../../../../../../etc/passwd%00",
    # r"The quic\b\b\b\b\b\bk brown fo\u0007\u0007\u0007\u0007\u0007\u0007\u0007\u0007\u0007\u0007\u0007x... [Beeeep]",
    # r"<body",
    # r"<vbscript",
    # r"<script",
    # r"<applet",
    # r"<embed",
    # r"<object",
    # r"<iframe",
    # r"<meta",
    # r"<style",
    # r"<div",
    # r"javascript:",
    # r"behavior:",
    # r"onabort",
    # r"onblur",
    # r"onchange",
    # r"onclick",
    # r"ondblclick",
    # r"ondragdrop",
    # r"onerror",
    # r"onfocus",
    # r"onkeydown",
    # r"onkeypress",
    # r"onkeyup",
    r"onload",
    # r"onmousedown",
    # r"onmousemove",
    # r"onmouseout",
    # r"onmouseover",
    # r"onmouseup",
    # r"onmove",
    # r"onreset",
    # r"onresize",
    # r"onselect",
    # r"onsubmit",
    # r"onunload",
    # r"!--",
    # r"&#",
    # r"\"",
    # r"&{",
    # r"@import",
    # r"-moz-binding",
    # r"document.cookie",
    # r"document.write",
    # r"fromcharcode"
]

non_xss_test_data = [
    r",./;'[]\-=",
    r"!@#$%^&*()`~",
    u"åß∂ƒ©˙∆˚¬…æ",
    u"田中さんにあげて下さい"
]
